---
title: "Subgroup Identification Analysis"
subtitle: "GBSG Example"
author: "Larry Leon"
toc: true
number-sections: true
toc-depth: 3
format: 
  html:
    self-contained: true
    code-fold: true
    bibliography: references.bib
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
    citation_package: natbib
    fig_width: 10
    fig_height: 8
    fontsize: 10pt
    extra_dependencies: "subfig"
---


```{r Setup, message=FALSE}
# Set options
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  fig.retina = 2
)
rm(list=ls())
library(tinytex)
library(ggplot2)

#library(table1)

library(gt)

library(survival)
library(data.table)
library(randomForest)
library(grf)
library(policytree)
library(DiagrammeR)

#library(grid)
#library(forestploter)

#library(randomizr)
# library(devtools)
# install_github("larry-leon/weightedsurv", force = TRUE)
#install.packages("weightedsurv")
# install_github("larry-leon/forestsearch", force = TRUE)


library(forestsearch)
library(weightedsurv)

#help(forestsearch)
#help(generate_aft_dgm_flex)

# Set theme for plots
theme_set(theme_minimal(base_size = 12))

```


# Summary

Reproducing main GBSG analysis 

## Datasetup  
```{r Datasetup}
df.analysis <- gbsg
df.analysis <- within(df.analysis,{
id <- as.numeric(c(1:nrow(df.analysis)))  
# time to months
time_months <- rfstime/30.4375
grade3 <- ifelse(grade=="3",1,0)
treat <- hormon
})
confounders.name <- c("age","meno","size","grade3","nodes","pgr","er")
outcome.name <- c("time_months")
event.name <- c("status")
id.name <- c("id")
treat.name <- c("hormon")



```


## Kaplan-Meier curves and baseline summary

```{r, fig.width = 7, fig.height = 5}

dfcount <- df_counting(
  df = df.analysis,
  by.risk = 6,
  tte.name = outcome.name, 
  event.name = event.name, 
  treat.name = treat.name
)
plot_weighted_km(dfcount, conf.int = TRUE, show.logrank = TRUE, ymax = 1.05, xmed.fraction = 0.775, ymed.offset = 0.125)
```


```{r}
create_summary_table(data = df.analysis, treat_var = treat.name, 
                     table_title = "GBSG Characteristics by Treatment Arm",
                                      vars_continuous=c("age","nodes","size","er","pgr"),
                                      vars_categorical=c("grade","grade3"),
                                      font_size = 12)
```


## GRF analysis  
```{r GRF, echo=TRUE, eval=TRUE}

## GRF
grf_est1 <- grf.subg.harm.survival(data=df.analysis,
confounders.name = confounders.name,
outcome.name=outcome.name, event.name=event.name, id.name=id.name, treat.name=treat.name,
maxdepth = 2, n.min = 60, dmin.grf = 12, frac.tau=0.6, details=TRUE)
```

```{r GRFtrees, echo=TRUE, eval=TRUE, fig.width = 7, fig.height = 5}
# NOTE: In general for GRF trees
# leaf1 --> recommend control
# leaf2 --> recommend treatment
# Tree depth 1
plot(grf_est1$tree1,leaf.labels=c("Control","Treat"))
# Tree depth 2
plot(grf_est1$tree2,leaf.labels=c("Control","Treat"))
```




## Forestsearch with depth=2 (maxk = 2)

```{r fs_k2, echo=TRUE, message=FALSE, warning=TRUE, fig.width = 10, fig.height = 8, eval = TRUE}

# Setup parallel processing
library(doFuture)
library(doRNG)

registerDoFuture()
registerDoRNG()

system.time({fs <- forestsearch(df.analysis,  confounders.name = confounders.name,
                                outcome.name = "time_months", treat.name = "hormon", event.name = "status", id.name = "id",
                                potentialOutcome.name = NULL, 
                                df.test = NULL,
                                flag_harm.name = NULL,
                                hr.threshold = 1.25, hr.consistency = 1.0, pconsistency.threshold = 0.90,
                                sg_focus = "maxSG", max_subgroups_search = 30,
                                showten_subgroups = TRUE, details=TRUE,
                                conf_force = c("age <= 65"),
                                cut_type = "default", use_grf = TRUE, plot.grf = TRUE, use_lasso = TRUE,
                                maxk = 2, 
                                n.min = 60, d0.min = 12, d1.min = 12,
                                plot.sg = TRUE, by.risk = 6,
                                parallel_args = list(plan="callr", workers = 30, show_message = TRUE)
)
})

plan("sequential")


# Results for estimation (training) data, which_df = "est" is default
res_tabs <- sg_tables(fs, ndecimals = 3, which_df = "est")

res_tabs$sg10_out

res_tabs$tab_estimates


```


## Bootstrap Inference

```{r, eval = FALSE}

#output_dir <- "dev/vignettes-working/applications/gbsg/results"
output_dir <- "results/"
save_results <- dir.exists(output_dir)

# patchhwork needed for a combined bootstrap plot (otherwise if not avaialable will not produce)
library(patchwork)

# Number of bootstrap samples
NB <- 1000

system.time({fs_bc <- forestsearch_bootstrap_dofuture(
  fs.est = fs, 
  nb_boots = NB, 
  show_three = FALSE, 
  details = TRUE)
})

plan("sequential")


if (save_results) {
    filename <- file.path(output_dir, 
                         paste0("gbsg_k2_B=", 
                                format(NB), 
                                ".RData"))
    save(fs_bc, fs, file = filename)
    cat("\nResults saved to:", filename, "\n")
}

```

### Diagnostics and Summaries

```{r}

#load("~/Documents/GitHub/forestsearch/vignettes/results/sim_gbsg_example_B=1000.RData")

output_dir <- "results/"


load_results <- dir.exists(output_dir)
NB <- 1000
if(load_results){
filename <- file.path(output_dir, 
                         paste0("gbsg_k2_B=", 
                                format(NB),".RData"))

load(file = filename)
}

summaries <- summarize_bootstrap_results(
      sgharm = fs$sg.harm,
      boot_results = fs_bc,
      create_plots = TRUE,
      est.scale = "hr"
    )

sg_tab <- summaries$table

sg_tab

event_summary <- summarize_bootstrap_events(fs_bc, threshold = 12)

summaries$diagnostics_table_gt

summaries$subgroup_summary$original_agreement

summaries$subgroup_summary$factor_presence

summaries$subgroup_summary$factor_presence_specific

```

```{r, fig.width = 10, fig.height = 8}

summaries$plots$combined

```



## Forestsearch with depth=1 (maxk = 1)

```{r fs_k1, echo=TRUE, message=FALSE, warning=TRUE, fig.width = 10, fig.height = 8, eval = TRUE}

# Setup parallel processing
library(doFuture)
library(doRNG)

registerDoFuture()
registerDoRNG()

system.time({fs <- forestsearch(df.analysis,  confounders.name = confounders.name,
                                outcome.name = "time_months", treat.name = "hormon", event.name = "status", id.name = "id",
                                potentialOutcome.name = NULL, 
                                df.test = NULL,
                                flag_harm.name = NULL,
                                hr.threshold = 1.25, hr.consistency = 1.0, pconsistency.threshold = 0.90,
                                sg_focus = "maxSG", max_subgroups_search = 30,
                                showten_subgroups = TRUE, details=TRUE,
                                conf_force = c("age <= 65"),
                                cut_type = "default", use_grf = TRUE, plot.grf = TRUE, use_lasso = TRUE,
                                maxk = 1, 
                                n.min = 60, d0.min = 12, d1.min = 12,
                                plot.sg = TRUE, by.risk = 6,
                                parallel_args = list(plan="callr", workers = 30, show_message = TRUE)
)
})

plan("sequential")


# Results for estimation (training) data, which_df = "est" is default
res_tabs <- sg_tables(fs, ndecimals = 3, which_df = "est")

res_tabs$sg10_out

res_tabs$tab_estimates


```


## Bootstrap Inference

```{r, eval = FALSE}

output_dir <- "results/"
save_results <- dir.exists(output_dir)

# patchhwork needed for a combined bootstrap plot (otherwise if not avaialable will not produce)
library(patchwork)

# Number of bootstrap samples
NB <- 1000

system.time({fs_bc <- forestsearch_bootstrap_dofuture(
  fs.est = fs, 
  nb_boots = NB, 
  show_three = FALSE, 
  details = TRUE)
})

plan("sequential")


if (save_results) {
    filename <- file.path(output_dir, 
                         paste0("gbsg_k1_B=", 
                                format(NB), 
                                ".RData"))
    save(fs_bc, fs, file = filename)
    cat("\nResults saved to:", filename, "\n")
}

```

### Diagnostics and Summaries

```{r}

output_dir <- "results/"
load_results <- dir.exists(output_dir)
NB <- 1000
if(load_results){
filename <- file.path(output_dir, 
                         paste0("gbsg_k1_B=", 
                                format(NB),".RData"))

load(file = filename)
}

summaries <- summarize_bootstrap_results(
      sgharm = fs$sg.harm,
      boot_results = fs_bc,
      create_plots = TRUE,
      est.scale = "hr"
    )

sg_tab <- summaries$table

sg_tab

event_summary <- summarize_bootstrap_events(fs_bc, threshold = 12)

summaries$diagnostics_table_gt

summaries$subgroup_summary$original_agreement

summaries$subgroup_summary$factor_presence

summaries$subgroup_summary$factor_presence_specific

```

```{r, fig.width = 10, fig.height = 8}

summaries$plots$combined

```
