\documentclass[9pt]{article}
\usepackage{amsmath}
\usepackage{graphicx,psfrag,epsf}
\usepackage{enumerate}
\usepackage{natbib}
\usepackage[colorlinks=true,linkcolor={blue},citecolor={blue},urlcolor={blue}]{hyperref}
\usepackage{longtable,ctable}
\usepackage{amssymb}
\usepackage{amsfonts}
\usepackage{multirow}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{mathptmx}
\usepackage{setspace}
\usepackage[utf8]{inputenc}
\usepackage{pgf}
\usepackage{algorithm}
\usepackage{algpseudocode}
\usepackage{threeparttable}
\usepackage{verbatim}
\usepackage{bm}
\usepackage{xcolor}



%\pdfminorversion=4
% NOTE: To produce blinded version, replace "0" with "1" below.
\newcommand{\blind}{0}

% DON'T change margins - should be 1 inch all around.
\addtolength{\oddsidemargin}{-.5in}%
\addtolength{\evensidemargin}{-.5in}%
\addtolength{\textwidth}{1in}%
\addtolength{\textheight}{1.3in}%
\addtolength{\topmargin}{-.8in}%


\newcommand{\R}{R}
\newcommand{\gbsg}{gbsg}
\def\FsNg{\hbox{FS-M}}

\def\hhat{\hat\theta(\widehat{H})}
\def\hchat{\hat\theta(\widehat{H}^{c})}

\def\hhatB{\hat\theta^{*}(\widehat{H})}
\def\hchatB{\hat\theta^{*}(\widehat{H}^{c})}


\def\hknow{\hat\theta(H)}
\def\hcknow{\hat\theta(H^{c})}

\def\hplim{\theta^{\dagger}(H)}
\def\hcplim{\theta^{\dagger}(H^{c})}
\def\hplimitt{\theta^{\dagger}(ITT)}

\def\fsl{FS_{l}}
\def\fslg{FS_{lg}}
\def\grfa{GRF}
\def\grfb{GRF_{60}}


\def\hhplim{\theta^{\ddagger}(H)}
\def\hhcplim{\theta^{\ddagger}(H^{c})}

\def\Hhplim{\theta^{\ddagger}(\widehat{H})}
\def\Hhcplim{\theta^{\ddagger}(\widehat{H}^{c})}

\def\hath{\widehat{H}}
\def\hathc{{\widehat{H}}^{c}}


\def\sumin{\sum_{i=1}^n}
\def\nsumin{n^{-1}\sum_{i=1}^n}

\newcommand{\indep}{\perp \!\!\! \perp}

\begin{document}

\def\spacingset#1{\renewcommand{\baselinestretch}%
{#1}\small\normalsize} \spacingset{1}


\if0\blind
{
  \title{\bf Exploratory subgroup identification in the heterogeneous Cox model: A relatively simple procedure}
  \date{}
  \author{Larry F. Le\'on %\thanks{}\hspace{.2cm}
  , Thomas Jemielita, \\ Zifang Guo, Rachel Marceau West, and Keaven Anderson \\
    Biostatistics and Research Decision Sciences, Merck \& Co., Inc., Rahway, NJ, USA}
  \maketitle
} \fi


\bigskip
\begin{center}
{\large\bf SUPPLEMENTARY MATERIALS}
\end{center}

Section S1.1 considers the accuracy of the $N(\beta,8/d)$ asymptotic approximation to the random splits of the FS algorithm where the sample size is $N=60$.  Section S2.1 provides an 
additional analysis of the GBSG dataset. Section S2.2 provides an additional analysis of the ACTG-175 dataset.  Sections S2.3 and S2.4 provide additional analyses of the ACTG-175 dataset
where we artificially add twenty $N(0,1)$ baseline factors as candidates: In Section S2.3 the FS algorithm does not include lasso, whereas in Section S2.4 lasso is included.  Section S2.5 evaluates 
the use of aspirin in the systolic heart failure data (\citealp{Hsich_2011}) available in the \verb+randomForestSRC+ package (\citealp{Ishwaran_2008}).  Lastly, in Section S3 we 
apply the subgroup definitions based on the GBSG analysis to the Rotterdam data \citep{Foekens_2000} which was utilized for ``external validation of a Cox prognostic model'' \citep{Royston_2013}.

R code and markdown files for replicating the analyses is available at the GitHub repository: \href{https://github.com/larry-leon/forestSearch}{https://github.com/larry-leon/forestSearch}. 
We note that an R package to be published on CRAN is under development.  Our code implements parallel computing via the \verb+doFuture+ package (\citealp{Bengtsson_2021}) for the bootstrapping and CV procedures; accordingly the timing of computations depends on the number of available cores.


<<echo=FALSE>>=
opts_chunk$set (warning = FALSE, message = FALSE, tidy=TRUE, echo=FALSE, dev = 'pdf', quietly=TRUE)
options(warn=-1)
@

<<echo=FALSE,message=FALSE,warning=FALSE>>=
load("results-input/simapprox_N=60_v0.Rdata")
# Plim of estimates
bplim<-mean(bhats_a)
xmin<--3
xmax<-3
d<-(1-mean(censors))*N/2
@

\section*{S1 Power approximations}


\section*{S1.1 Simulation evaluation of $\hat\beta \sim N(\beta,4/d)$ approximation accuracy} \label{sec:Napprox}

For the random splitting of the FS algorithm we approximate the separate splits via $\hat\beta_{s}^{1} \sim N(\beta,8/d)$ and independently $\hat\beta_{s}^{2} \sim N(\beta,8/d)$.  Define
$\hat\beta_{s}$ as the Cox model estimate for the subgroup.  Since the splits are purely random (the artificially stratified Cox model estimate will be approximately the same as $\hat\beta_{s}$) we have 
$\hat\beta_{s}^{1} + \hat\beta_{s}^{2} \approx 2 \hat\beta_{s}$.

Figure \ref{fig:Napprox} is based on 20,000 simulations where we generate $N=60$ subjects from a Cox model with (true) $\beta \approx \Sexpr{round(mean(bhats_a),3)}$ with number of events (on average) $=\Sexpr{round(2*d,1)}$.
Figure \ref{fig:Napprox}(a) plots the empirical cdf (ECDF) of the 20,000 estimates corresponding to the first split ($\hat\beta_{s}^{1}$) along with the $N(\beta,8/d)$ approximation.  Similarly, 
Figure \ref{fig:Napprox}(b) displays the results for the corresponding second split ($\hat\beta_{s}^{2}$).   Figure \ref{fig:Napprox}(c) plots the ECDF of 20,000 $(\hat\beta_{s}^{1} + \hat\beta_{s}^{2})$'s, along with the ECDF of 20,000 $2\hat\beta_{s}$'s.  Figure \ref{fig:Napprox}(d) plots the ECDF of 20,000 $\min(\hat\beta_{s}^{1},\hat\beta_{s}^{2})$'s along with the $1-(1-N(\beta,8/d)^{2})$ approximation.

\begin{figure}[h]
\begin{center}
<<sim_approxH-S1,echo=FALSE>>=
par(mfrow=c(2,2))
plot(ecdf(b1hats),xlim=c(xmin,xmax),xlab="b1hat",ylab="Fn(b1hat)",main="ECDF of strata 1 (b1hat)")
title(sub="(a)")
xx<-sort(b1hats)
approx_normal<-pnorm(xx,mean=bplim,sd=sqrt(4/d))
lines(xx,approx_normal,type="s",lwd=1,col="blue")
#legend(1.5,0.95,c("b1hat","N(beta,8/d)"),lwd=1,col=c("black","blue"),bty="n")
legend("topleft",c("b1hat","N(beta,8/d)"),lwd=1,col=c("black","blue"),bty="n")

plot(ecdf(b2hats),xlim=c(xmin,xmax),xlab="b2hat",ylab="Fn(b2hat)",main="ECDF of strata 2 (b2hat)")
title(sub="(b)")
xx<-sort(b2hats)
approx_normal<-pnorm(xx,mean=bplim,sd=sqrt(4/d))
lines(xx,approx_normal,type="s",lwd=1,col="blue")
#legend(1.5,0.95,c("b2hat","N(beta,8/d)"),lwd=1,col=c("black","blue"),bty="n")
legend("topleft",c("b2hat","N(beta,8/d)"),lwd=1,col=c("black","blue"),bty="n")

xx<-b1hats+b2hats
yy<-2*bhats_a
oo<-order(xx)
xx<-xx[oo]
yy<-yy[oo]

plot(ecdf(b1hats+b2hats),xlim=c(xmin,xmax),xlab="b1hat+b2hat",ylab="Fn(b1hat+b2hat)",main="ECDF of b1hat+b2hat")
title(sub="(c)")
lines(ecdf(2*bhats_a),lwd=1,col="blue")
#legend(1.5,0.95,c("b1hat+b2hat","2*bhat"),lwd=1,col=c("black","blue"),bty="n")
legend("topleft",c("b1hat+b2hat","2*bhat"),lwd=1,col=c("black","blue"),bty="n")

plot(ecdf(bhats_min),xlim=c(xmin,xmax),xlab="min(b1hat,b2hat)",ylab="Fn(min(b1hat,b2hat))",main="ECDF of min(b1hat,b2hat)")
title(sub="(d)")
xx<-sort(bhats_min)
Qb<-pnorm(xx,mean=bplim,sd=sqrt(4/d))
approx_normal<-1-(1-Qb)^2
lines(xx,approx_normal,type="s",lwd=1,col="blue")
#legend(1.0,0.95,c("min(b1hat,b2hat)","1-(1-N(.,beta,8/d)^2)"),lwd=1,col=c("black","blue"),bty="n")
legend("topleft",c("min(b1hat,b2hat)","1-(1-N(.,beta,8/d)^2)"),lwd=1,col=c("black","blue"),bty="n")
@
\end{center}
\caption{Accuracy of normal approximation $\hat\beta \approx N(\beta,8/d)$}
\label{fig:Napprox}
\end{figure}


\section*{S1.2 Power approximations for censoring rates of $0\%$ and $80\%$}

<<echo=FALSE,message=FALSE,warning=FALSE,eval=TRUE>>=
load("results-input//pAnyH_approx_nsg_nocensoring.Rdata")
mdd.60<-min(hrH.plims[pAnyH.approx.60>=0.80])
mdd.80<-min(hrH.plims[pAnyH.approx.80>=0.80])
mdd.100<-min(hrH.plims[pAnyH.approx.100>=0.80])

# e for type-1 error
Edd.60<-max(hrH.plims[pAnyH.approx.60<=0.10])
Edd.80<-max(hrH.plims[pAnyH.approx.80<=0.10])
Edd.100<-max(hrH.plims[pAnyH.approx.100<=0.10])

# Look at thetaH around 0.80 (considering beneficial)
loc.beni <- min(which(hrH.plims>=0.75))
beni_hr <- round(hrH.plims[loc.beni],2)
alpha.beni.60 <-pAnyH.approx.60[loc.beni]
alpha.beni.80 <-pAnyH.approx.80[loc.beni]
alpha.beni.100 <-pAnyH.approx.100[loc.beni]
@

<<echo=FALSE,message=FALSE,warning=FALSE,eval=FALSE>>=
# For paper
pdf(file = "plot_approxH_nocensoring.pdf",   
width = 10, height = 10) 
library(latex2exp)
plot(hrH.plims,pAnyH.approx.60,xlab="Hazard ratio for subgroup H",ylab="Probability of any H found",type="l",lty=1,lwd=2.0,ylim=c(0,1))
abline(h=0.10,lwd=0.5,col="red")
lines(hrH.plims,pAnyH.approx.80,type="l",lty=1,lwd=2,col="grey")
lines(hrH.plims,pAnyH.approx.100,type="l",lty=1,lwd=2,col="blue")
legend("topleft",
legend=TeX(sprintf(r'($n = %d$)',c(60,80,100))),
lty=1,lwd=2,col=c("black","grey","blue"),bty="n")
dev.off()
@

\begin{figure*}
\begin{center}
\includegraphics[width=5.5in, height=3.25in]{plot_approxH_nocensoring.pdf}
\end{center}
\caption{Approximate probability of finding H via FS: Subgroup $H$ of size $n=60, 80, 100$ exists with underlying hazard-ratio varying from 0.5 to 3.0 and with assumed average censoring rate of $0\%$ so that $d = n$.  The horizontal line indicates $10\%$. Approximately $80\%$ reached at underlying hazard-ratios of $\Sexpr{round(mdd.60,2)}$, $\Sexpr{round(mdd.80,2)}$, and $\Sexpr{round(mdd.100,2)}$, for $n$ = 60, 80, and 100, respectively. \label{fig:ApproxH_nocensoring}}
\end{figure*}

Figure {\ref{fig:ApproxH_nocensoring}} displays the approximate power under no censoring for scenarios where a subgroup $H$ exists ($n=$ 60, 80, or 100) with underlying hazard-ratio for subgroup $H$ varying from $0.5$ to $3.0$.
For $\hplim \equiv \hplimitt = \Sexpr{beni_hr}$, the approximation is $\Sexpr{round(alpha.beni.60,3)}$, $\Sexpr{round(alpha.beni.80,3)}$, and $\Sexpr{round(alpha.beni.100,3)}$ for $n=60$, $80$, and $100$, respectively.

<<echo=FALSE,message=FALSE,warning=FALSE,eval=TRUE>>=
load("results-input//pAnyH_approx_nsg_heavycensoring.Rdata")
mdd.60<-min(hrH.plims[pAnyH.approx.60>=0.80])
mdd.80<-min(hrH.plims[pAnyH.approx.80>=0.80])
mdd.100<-min(hrH.plims[pAnyH.approx.100>=0.80])

# e for type-1 error
Edd.60<-max(hrH.plims[pAnyH.approx.60<=0.10])
Edd.80<-max(hrH.plims[pAnyH.approx.80<=0.10])
Edd.100<-max(hrH.plims[pAnyH.approx.100<=0.10])

# Look at thetaH around 0.80 (considering beneficial)
loc.beni <- min(which(hrH.plims>=0.75))
beni_hr <- round(hrH.plims[loc.beni],2)
alpha.beni.60 <-pAnyH.approx.60[loc.beni]
alpha.beni.80 <-pAnyH.approx.80[loc.beni]
alpha.beni.100 <-pAnyH.approx.100[loc.beni]
@

<<echo=FALSE,message=FALSE,warning=FALSE,eval=FALSE>>=
# For paper
pdf(file = "plot_approxH_heavycensoring.pdf",   
width = 10, height = 10) 
library(latex2exp)
plot(hrH.plims,pAnyH.approx.60,xlab="Hazard ratio for subgroup H",ylab="Probability of any H found",type="l",lty=1,lwd=2.0,ylim=c(0,1))
abline(h=0.10,lwd=0.5,col="red")
lines(hrH.plims,pAnyH.approx.80,type="l",lty=1,lwd=2,col="grey")
lines(hrH.plims,pAnyH.approx.100,type="l",lty=1,lwd=2,col="blue")
legend("topleft",
legend=TeX(sprintf(r'($n = %d$)',c(60,80,100))),
lty=1,lwd=2,col=c("black","grey","blue"),bty="n")
dev.off()
@

\begin{figure*}
\begin{center}
\includegraphics[width=5.5in, height=3.25in]{plot_approxH_heavycensoring.pdf}
\end{center}
\caption{Approximate probability of finding H via FS: Subgroup $H$ of size $n=60, 80, 100$ exists with underlying hazard-ratio varying from 0.5 to 3.0 and with assumed average censoring rate of $80\%$ so that $d \approx 0.20n$.  The horizontal line indicates $10\%$. Approximately $80\%$ reached at underlying hazard-ratios of $\Sexpr{round(mdd.60,2)}$, $\Sexpr{round(mdd.80,2)}$, and $\Sexpr{round(mdd.100,2)}$, for $n$ = 60, 80, and 100, respectively. \label{fig:ApproxH_heavycensoring}}
\end{figure*}

Figure {\ref{fig:ApproxH_heavycensoring}} displays the approximate power under heavy censoring of $80\%$ for scenarios where a subgroup $H$ exists ($n=$ 60, 80, or 100).
Here, for $\hplim \equiv \hplimitt = \Sexpr{beni_hr}$, the approximation is $\Sexpr{round(alpha.beni.60,3)}$, $\Sexpr{round(alpha.beni.80,3)}$, and $\Sexpr{round(alpha.beni.100,3)}$ for $n=60$, $80$, and $100$, respectively.  However, note that these calculations do not take into account the $d \geq 20$ requirement of the FS procedure which would not be generally met for subgroup sample sizes of $60$ and $80$, here.


\section*{S2 Additional analyses}

\Sexpr{knit_child("gbsg_supplementary_v0.Rnw")}

\Sexpr{knit_child("actg175_supplementary_v0.Rnw")}

\Sexpr{knit_child("actg175_noisey_supplementary_v0.Rnw")}

\Sexpr{knit_child("actg175_noisey+lasso_supplementary_v0.Rnw")}

\Sexpr{knit_child("shf_v0.Rnw")}

\section*{S3 GBSG subgroup definitions applied to Rotterdam tumor bank dataset}

\Sexpr{knit_child("gbsg_validate_supplementary_v0.Rnw")}


\bibliographystyle{plainnat} 
\bibliography{subgroups_ref}


\end{document}